version: 2
jobs:
  client-build:
    working_directory: ~/full-app
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "client/package.json" }}
      - run:
          name: install-npm
          command: npm install --prefix client
      - save_cache:
          key: dependency-cache-{{ checksum "client/package.json" }}
          paths:
            - ./client/node_modules
      - run:
          name: lint
          command: npm run lint --prefix client
      - run:
          name: test
          command: npm run test --prefix client
  server-build:
    working_directory: ~/full-app
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "server/package.json" }}
      - run:
          name: install-npm
          command: npm install --prefix server
      - save_cache:
          key: dependency-cache-{{ checksum "server/package.json" }}
          paths:
            - ./server/node_modules
      - run:
          name: lint
          command: npm run lint --prefix server
workflows:
  version: 2
  build:
    jobs:
      - client-build
      - server-build